"""Add is_public and share_token to UserDB

Revision ID: a9bb1502e0a0
Revises: 67260f33c847
Create Date: 2026-09-13 13:35:21.455380

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a9bb1502e0a0'
down_revision: Union[str, Sequence[str], None] = '67260f33c847'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('share_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_share_token'), 'users', ['share_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_share_token'), table_name='users')
    op.drop_column('users', 'share_token')
    op.drop_column('users', 'is_public')
    # ### end Alembic commands ###
