"""Add price

Revision ID: b82c78dd37bf
Revises: a9bb1502e0a0
Create Date: 2026-09-15 20:34:56.148812

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b82c78dd37bf'
down_revision: Union[str, Sequence[str], None] = 'a9bb1502e0a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('watches', sa.Column('price', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('watches', 'price')
    # ### end Alembic commands ###
